---
resources:
- name: this
  type: git
  source:
    uri: https://github.com/ships/apt-repo-resource
    ignore_paths: [pipeline.yml]

- name: base-alpine
  type: docker-image
  source:
    repository: python
    tag: 3.6-alpine

- name: image
  type: docker-image
  source:
    repository: eveships/apt-repo-resource
    username: ((dockerhub_ships.username))
    password: ((dockerhub_ships.password))

jobs:
- name: rebuild
  plan:
  - in_parallel:
    - get: base-alpine
      trigger: true
    - get: this
      trigger: true
  - put: image
    params:
      build: this/
